### ISSUE TITLE
race conditions

### ISSUE THREAD

**Issue by Spacechild1** [Lucarda/pd-websocketserver#2]
The functions `onopen`, `onclose` and `onmessage` seem to be called from the network thread, but they call Pd API methods that are not thread-safe, e.g. `outlet_list` or `outlet_float`. You have to either

a) protect Pd with `sys_lock` + `sys_unlock` before/after calling such methods

or

b) use a thread-safe queue which is polled regularly from Pd's scheduler with a clock.

**Comment by Lucarda** [comment]
thanks!

I'll study this.

I might come back to you for further pointers on this :)

**Comment by Lucarda** [comment]
@Spacechild1 can you give a look to https://github.com/Lucarda/pd-websocketserver/tree/v0.0.1 ?
I think it solves the issue.

Edit
Easier to look via https://github.com/Lucarda/pd-websocketserver/pull/3/files

**Comment by Lucarda** [comment]
Closed via 21b99ad
